[package]
name = "morshd"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Next-generation remote terminal daemon over QUIC and TLS 1.3"
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "morshd"
path = "src/main.rs"

[dependencies]
morsh-core.workspace = true
morsh-transport.workspace = true
morsh-auth.workspace = true
morsh-term.workspace = true
morsh-tunnel.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
tokio.workspace = true
clap.workspace = true
clap_complete.workspace = true
clap_mangen.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
serde.workspace = true
toml.workspace = true

